instrumentation:
  include-all-sources: true
  extensions:
    - .js
    - .jsx
  excludes:
    - docs/**
    - scripts/**
    - webpack.config.js
reporting:
  print: summary
  reports:
  - html
  - text
check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
